### PR TITLE
Using flatten json

### PR DESCRIPTION
**Pull request by Arun-bioinformatics**
modified:   bin/utils.py
- updated get_sample_lists() to get sample IDs from only the given Sample Sheet
- Included new function get_key_value() and get_multiqc_data()
-  deleted functions get_control_lists() and get_sample_data()
- Bugfix: updated get_status()

modified:   full_assembly.py
- moved all argparse lines into parse_args() function
- moved rest of lines into main()

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, 1 of 1 files at r2, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3)* status: 6 of 8 files reviewed, 10 unresolved discussions (waiting on @Arun-bioinformatics)

___
*[`full_assembly.py` line 15 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8T_sF2RNtVTZznIcO:-Ne8T_sG4cWK9Pnq2OBw:b-r1gpl5) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/full_assembly.py#L15)):*
> ```Python
>     {
>      SampleID:[
>                HeaderID:{
> ```

does this reflect what is now output?



_Code quote:_
```Python
Output:

    {
     SampleID:[
               HeaderID:{
```
___
*[`full_assembly.py` line 60 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8TnPv39prF7yCd6Ig:-Ne8TnPw7Iji_TzDWrPr:bpi2n5i) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/full_assembly.py#L60)):*
> ```Python
>     # List of samples
>     sample_sheet = args.samplesheet
>     sample_list = Classifier.get_sample_lists(sample_sheet)
> ```

there's no real need to assign individual args to variables to then pass into functions (i.e. this can be `sample_list = Classifier.get_sample_lists(args.samplesheet)`, it makes sense more if you're going to reuse it repeatedly or etc but for this I'd save the lines and just pass it directly (same below where args are used)



_Code quote:_
```Python
    sample_sheet = args.samplesheet
    sample_list = Classifier.get_sample_lists(sample_sheet)
```
___
*[`bin/utils.py` line 24 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8UdG16uDqhmYoL3Fl:-Ne8UdG28bEFqOTm2gUV:bw5f8ey) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/bin/utils.py#L24)):*
> ```Python
>         - Config Field
>     Output:
>         - Header ID
> ```

can you update these to include types and a description like others



_Code quote:_
```Python
    Input:
        - Config Field
    Output:
        - Header ID
```
___
*[`bin/utils.py` line 77 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8UqCl-TDmIFBujE-7:-Ne8UqCl-TDmIFBujE-8:bh30wz4) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/bin/utils.py#L77)):*
> ```Python
>     Input: 
>         multiqc_data (variable which must have gone through json.load())
>             i.e.: multiqc_data = json.load(open("multiqc_data.json"))
> ```

input not present to function



_Code quote:_
```Python
        multiqc_data (variable which must have gone through json.load())
            i.e.: multiqc_data = json.load(open("multiqc_data.json"))
```
___
*[`bin/utils.py` line 89 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8V5l02bwKJZJqjipW:-Ne8V5l16wYbsasLxCsG:bf5f45v) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/bin/utils.py#L89)):*
> ```Python
>     # Get all IDs from sample sheet
>     with open(csv_filepath, 'r', encoding='UTF-8') as file:
>         sample_sheet = pandas.read_csv(file, skiprows=20)
> ```

the samplesheet spec is fairly loose and the side of the header before sample rows is variable dependent on what options are added to the samplesheet (which can be added to provide inputs to demultiplexing), I'd recommend doing what is done here and indexing off `Sample_ID` (which will always be in the samplesheet): https://github.com/eastgenomics/eggd_conductor/blob/262d9abcd20bf141a92d9f59fe3498cfe48d0dc7/resources/home/dnanexus/run_workflows/run_workflows.py#L48

if you're interested you can read more on samplesheet spec here: https://support-docs.illumina.com/SW/DRAGEN_v39/Content/SW/DRAGEN/SampleSheet.htm



_Code quote:_
```Python
skiprows=20)
```
___
*[`bin/utils.py` line 95 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8W_2EAqtjuQNjTWu4:-Ne8W_2EAqtjuQNjTWu5:b-58so6z) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/bin/utils.py#L95)):*
> ```Python
> 
> 
> # create a function that extracts all the data that we need given the multiqc.json
> ```

needed?



_Code quote:_
```Python
# create a function that extracts all the data that we need given the multiqc.json
```
___
*[`bin/utils.py` line 114 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8Whdc2o2dVJ4aU7t-:-Ne8Whdc2o2dVJ4aU7t0:b-ublju2) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/bin/utils.py#L114)):*
> ```Python
>     return data
> 
> # create a function which returns you a value given the sample ID and parameter
> ```

also needed?



_Code quote:_
```Python
 create a function which returns you a value given the sample ID and parameter
```
___
*[`bin/utils.py` line 119 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8X0BW-omI48gts2pU:-Ne8X0BW-omI48gts2pV:bb7phvt) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/bin/utils.py#L119)):*
> ```Python
> 
>     Args:
>         summarised_data (dictionar): multiqc_data obtained from get_multiqc_data().
> ```

typo



_Code quote:_
```Python
dictionar
```
___
*[`bin/utils.py` line 121 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8X2nW9wV47ANNfq1M:-Ne8X2nW9wV47ANNfq1N:bo418n9) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/bin/utils.py#L121)):*
> ```Python
>         summarised_data (dictionar): multiqc_data obtained from get_multiqc_data().
>         sample_id (str): Sample ID obtained from SampleSheet.csv
>         header_id (str): Output of map_header_id(config_field)
> ```

can you add to here what it actually is? (i.e. is it a config field name etc)



_Code quote:_
```Python
Output of map_header_id(config_field)
```
___
*[`bin/utils.py` line 170 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8X_UaAzZwAxQzfjr4:-Ne8X_UaAzZwAxQzfjr5:bx5g0iw) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/bin/utils.py#L170)):*
> ```Python
>             if condition.get('gt') or condition.get('gt') == 0:
>                 if float(value) > float(condition.get('gt')):
>                     #print(f"gt than {condition['gt']}")
> ```

can the commented prints be removed?



_Code quote:_
```Python
 #print(f"gt than {condition['gt']}")
```

**Review by Arun-bioinformatics — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3)* status: 6 of 8 files reviewed, 9 unresolved discussions (waiting on @jethror1)

___
*[`full_assembly.py` line 15 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8T_sF2RNtVTZznIcO:-Ne8gnbS4hYoxfVTpZJV:b-eqxhtl) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/full_assembly.py#L15)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

does this reflect what is now output?
</blockquote></details>

No, updated in next version.
___
*[`full_assembly.py` line 60 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8TnPv39prF7yCd6Ig:-Ne8hfzo3TG4TQjwdraL:b-896fix) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/full_assembly.py#L60)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

there's no real need to assign individual args to variables to then pass into functions (i.e. this can be `sample_list = Classifier.get_sample_lists(args.samplesheet)`, it makes sense more if you're going to reuse it repeatedly or etc but for this I'd save the lines and just pass it directly (same below where args are used)
</blockquote></details>

Done.
___
*[`bin/utils.py` line 24 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8UdG16uDqhmYoL3Fl:-Ne8j5Lq4e3dLZXabpUq:b-896fix) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/bin/utils.py#L24)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you update these to include types and a description like others
</blockquote></details>

Done.
___
*[`bin/utils.py` line 77 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8UqCl-TDmIFBujE-7:-Ne8lQTz6SgXSB9F9XJ-:bqkv7mn) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/bin/utils.py#L77)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

input not present to function
</blockquote></details>

Docstring updated
___
*[`bin/utils.py` line 89 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8V5l02bwKJZJqjipW:-Ne8owi81z7IK1t8m5Lo:b73xre) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/bin/utils.py#L89)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

the samplesheet spec is fairly loose and the side of the header before sample rows is variable dependent on what options are added to the samplesheet (which can be added to provide inputs to demultiplexing), I'd recommend doing what is done here and indexing off `Sample_ID` (which will always be in the samplesheet): https://github.com/eastgenomics/eggd_conductor/blob/262d9abcd20bf141a92d9f59fe3498cfe48d0dc7/resources/home/dnanexus/run_workflows/run_workflows.py#L48

if you're interested you can read more on samplesheet spec here: https://support-docs.illumina.com/SW/DRAGEN_v39/Content/SW/DRAGEN/SampleSheet.htm
</blockquote></details>

That is really useful to know, thanks! I have updated this in the next version.
___
*[`bin/utils.py` line 95 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8W_2EAqtjuQNjTWu4:-Ne8pCUV6P6nFLWIPQlM:b-896fix) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/bin/utils.py#L95)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

needed?
</blockquote></details>

Done.
___
*[`bin/utils.py` line 114 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8Whdc2o2dVJ4aU7t-:-Ne8pFCfAeqvTJewMNHo:b-896fix) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/bin/utils.py#L114)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

also needed?
</blockquote></details>

Done.
___
*[`bin/utils.py` line 121 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8X2nW9wV47ANNfq1M:-Ne8qSo50UvfBpdk3xlj:bpnqdng) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/bin/utils.py#L121)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you add to here what it actually is? (i.e. is it a config field name etc)
</blockquote></details>

Done, clarified in next version
___
*[`bin/utils.py` line 170 at r3](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne8X_UaAzZwAxQzfjr4:-Ne8qYMLCdRNQxZ9kh8D:b-pyy9ci) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/d6b1ee3f1d4e83d689fe97da0c1dd34a32d039e5/bin/utils.py#L170)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can the commented prints be removed?
</blockquote></details>

Done. yes

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @Arun-bioinformatics)

___
*[`full_assembly.py` line 131 at r5](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne93vURDvlUDvrgeDRP:-Ne93vUSCMKHEZFDxkB5:bxp8cwf) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/2dfe1f9e206119757ca7b814da3f96248c6d8d24/full_assembly.py#L131)):*
> ```Python
> 
>     # Saving output
>     with open('qc_report.json', 'w', encoding='UTF-8') as output_filename:
> ```

can we name the output file something specific to the run? maybe use the report name / title from the data json



_Code quote:_
```Python
qc_report.json
```

**Review by Arun-bioinformatics — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`full_assembly.py` line 131 at r5](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-Ne93vURDvlUDvrgeDRP:-NeCy54H038vaUizgsPY:bb6un1j) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/2dfe1f9e206119757ca7b814da3f96248c6d8d24/full_assembly.py#L131)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can we name the output file something specific to the run? maybe use the report name / title from the data json
</blockquote></details>

Done

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, 1 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @Arun-bioinformatics)

___
*[`bin/utils.py` line 217 at r7](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-NeHo2YZ9QK9InhUF7u3:-NeHo2Y_7mcgCY26XNvA:b-63ue7l) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/2f1b8495598c9b36aa8356cd668430f79cd62997/bin/utils.py#L217)):*
> ```Python
>     """
>     output_filename = re.search("[0-9]{6}_[A-Z0-9]{6}_[0-9]{4}_[A-Z0-9a-z_-]+multiqc",
>                                 summarised_data["report_multiqc_command"]).group()
> ```

I'd be cautious of directly calling `.group()` in case the regex doesn't match as it will raise an error (i.e. run naming changes or this is for some dev work where the title is different), I'd probably go with something like:
```
match = re.search(
    "[0-9]{6}_[A-Z0-9]{6}_[0-9]{4}_[A-Z0-9a-z_-]+multiqc",
    summarised_data["report_multiqc_command"]
)

if match:
    return f"{match.group()}.json"
else:
    print(
        "Run ID could not be parsed from 'report_multiqc_command' field in multiqc json: "
        f"{summarised_data["report_multiqc_command"]}.\nWriting to multiqc_qc_classified.json"
    )
    return 'multiqc_qc_classified.json'

```

I'd also add something to the end of the name to be clear its the file with classified / assessed qc output, but can decide on that later



_Code quote:_
```Python
    output_filename = re.search("[0-9]{6}_[A-Z0-9]{6}_[0-9]{4}_[A-Z0-9a-z_-]+multiqc",
                                summarised_data["report_multiqc_command"]).group()
```

**Review by Arun-bioinformatics — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`bin/utils.py` line 217 at r7](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3#-NeHo2YZ9QK9InhUF7u3:-NeJ21Ru6As4TKDr_7S8:b-18tsoz) ([raw file](https://github.com/eastgenomics/QC_Classifier/blob/2f1b8495598c9b36aa8356cd668430f79cd62997/bin/utils.py#L217)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I'd be cautious of directly calling `.group()` in case the regex doesn't match as it will raise an error (i.e. run naming changes or this is for some dev work where the title is different), I'd probably go with something like:
```
match = re.search(
    "[0-9]{6}_[A-Z0-9]{6}_[0-9]{4}_[A-Z0-9a-z_-]+multiqc",
    summarised_data["report_multiqc_command"]
)

if match:
    return f"{match.group()}.json"
else:
    print(
        "Run ID could not be parsed from 'report_multiqc_command' field in multiqc json: "
        f"{summarised_data["report_multiqc_command"]}.\nWriting to multiqc_qc_classified.json"
    )
    return 'multiqc_qc_classified.json'

```

I'd also add something to the end of the name to be clear its the file with classified / assessed qc output, but can decide on that later
</blockquote></details>

Done. Will decide later on how to end qc output file

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/QC_Classifier/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Arun-bioinformatics)

**Pull request merged**
